import pdf from 'html-pdf'
import Handlebars from 'handlebars'

export const create = function (document, options?) {
  return new Promise((resolve, reject) => {
    if (!document || !document.html || !document.data) {
      reject(new Error("Some, or all, options are missing."))
    }
    // Compiles a template
    const html = Handlebars.compile(document.html)(document.data, {
      allowProtoMethodsByDefault: true,
      allowProtoPropertiesByDefault: true
    })
    const pdfPromise = pdf.create(html, options)

    // Create PDF from html template generated by handlebars
    // Output will be PDF file
    pdfPromise.toFile(document.path, (err, res) => {
      if (!err)
        resolve(res)
      else
        reject(err)
    })
  })
}